### ISSUE TITLE
Space Ranger V2 support

### ISSUE THREAD

**Issue by constantin-zackl** [drighelli/SpatialExperiment#108]
Hi everyone, 

in the new Space Ranger V2 there have been changes to the output file definitions, causing an error when loading spatial data created with the new pipeline version with `read10xVisium()`. 

Shortly: The `tissue_positions_list.csv` has been renamed to `tissue_positions.csv` and now contains a header. 

Due to the fixed filename the new files can't be found: 
https://github.com/drighelli/SpatialExperiment/blob/25c25cd9747279c5dd293b2aa5e12398e92bf851/R/read10xVisium.R#L126

In addition the newly introduced header will result in a "is.numeric() is not TRUE" error due to line 189: 
https://github.com/drighelli/SpatialExperiment/blob/25c25cd9747279c5dd293b2aa5e12398e92bf851/R/read10xVisium.R#L181-L197

Space Ranger V2 release notes with changed file definition: https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/release-notes#:~:text=Space%20Ranger%201.3,Added%20header%20row)

10X sample dataset (V2): https://www.10xgenomics.com/resources/datasets/human-lung-cancer-ffpe-2-standard

Greetings, 
Constantin

**Comment by lmweber** [comment]
Hi @constantin-zackl , thank you for mentioning this!

Yes, we will need to update this for compatibility with both versions.

**Comment by HelenaLC** [comment]
Just a note that PR #109 is awaiting approval & should resolve this.

**Comment by drighelli** [comment]
Thanks, Helena (@HelenaLC)!!! 
I reviewed and commented on it!

**Comment by lmweber** [comment]
Done in PR #109 . Thank you!
