### ISSUE TITLE
Error in creating `RemoteSpatialImage`

### ISSUE THREAD

**Issue by lgeistlinger** [drighelli/SpatialExperiment#132]
Trying to create a remote spatial image around a CyCIF mask on Bioconductor's OpenStorageNetwork, but running into a problem: 

```
> f <- "https://mghp.osn.xsede.org/bir190004-bucket01/TMA11/segmentation/cell_masks/1.tif"
> SpatialExperiment::SpatialImage(f, is.url = TRUE)
3007 x 3007 (width x height) RemoteSpatialImage
Error in .local(x, ...) : argument "path" is missing, with no default
```

**Comment by LiNk-NY** [comment]
I also see this error when I run the first example in `test_SpatialImage-methods.R`: 

``` r
suppressPackageStartupMessages(library(SpatialExperiment))
url <- "https://i.redd.it/3pw5uah7xo041.jpg"
spi <- new("RemoteSpatialImage", url=url)
spi
#> 1200 x 1186 (width x height) RemoteSpatialImage
#> Error in .local(x, ...): argument "path" is missing, with no default
```

<sup>Created on 2022-11-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by HelenaLC** [comment]
Apologues, PR #113 should have resolved this & is awaiting moderation.

**Comment by HelenaLC** [comment]
Should be resolved with the next Bioc built (on devel for now)...
