### ISSUE TITLE
Implement SpatialSpotExperiment and SpatialMoleculeExperiment sub-classes

### ISSUE THREAD

**Issue by lmweber** [drighelli/SpatialExperiment#14]
As discussed during and after EuroBioc2020 BoF workshop: re-structure the class as follows:

- main (virtual) super-class called `SpatialExperiment` (which is not directly used by users)
- sub-class `SpatialSpotExperiment` for spot-based technologies, e.g. Visium, Slide-seq
- sub-class `SpatialMoleculeExperiment` for molecule-based technologies, e.g. seqFISH, MERFISH

**Comment by lmweber** [comment]
Change of plans - it is simpler for users to have a single class name (as long as this works).

For now, we will try to structure it as a single class called `SpatialExperiment` only, with empty slots for parts that are not applicable for a given technology.

**Comment by LTLA** [comment]
What do the molecule people need? Bioconductor/Contributions#1817 BTW.

**Comment by lmweber** [comment]
Ok I get it now with this `BumpyMatrix`. This is very cool.

For the molecule-based, we could store it as:

- main assay (genes x cells) containing gene counts
- `altExp` containing a `BumpyMatrix` with the x-y coordinates of each mRNA molecule per gene per cell. This needs to be bumpy, since the number of molecules per gene per cell varies (and in fact the length of each bump is equal to the value of the counts in the main assay)
- `colData` also contains the numeric list of segmentation vertices (x-y coordinates of the vertices) for each cell, in the format that Shila has currently stored them for seqFISH data

I'm working on an example using Shila's seqFISH dataset, although to finish we will need to push our current version of `SpatialExperiment` to Bioc-devel so I can install it alongside `BumpyMatrix` (I'm getting a bunch of errors due to dependencies when I try to install `SpatialExperiment` in devel from GitHub).

**Comment by lmweber** [comment]
And if this works, we probably can indeed store everything in the base `SpatialExperiment`, without the two subclass names.

Although there will be a bunch of arguments in the main `SpatialExperiment()` constructor that are only relevant for one or the other. Maybe that is fine.

The advantage of having only a single class name is we also don't need to add new ones in the future if some new technology comes along, which doesn't fit conceptually into the "spot-based" or "molecule-based" groups.

**Comment by lmweber** [comment]
@LTLA can we put a 1-dimensional `BumpyMatrix` (`BumpyVector`?) inside `colData` to store the segmentation vertices (data frame of x-y coordinates of the vertices) of each cell? Or alternatively maybe as another `altExp` (with only 1 row).

**Comment by HelenaLC** [comment]
Re verices: I think these can be simpler - e.g., `x_coord` & `y_coord` store cell centroids so that `spatstat`-derived functions and `ggspavis` visualizations still work; vertices could go into a `vertices` column which is a list of `data.frame` or `matrix` with rows = vertex, columns = coordinates.  
In other news, there was some mention during EuroBioc about using graph-based structures for this instead (I think Aedin mentioned `igraph`?) which would support polygon stuff (I don't know what that is exactly... but remember her saying this was important for cell-to-cell interactions etc.)

**Comment by LTLA** [comment]
Note that the `BumpyDFrameMatrix` for the transcript locations need not be in an alternative experiment; this can be just another assay in the SPE, as the dimensions are the same. 

The vertices can be stored as a `CompressedSplitDFrameList` in the `colData, which is the one-dimensional equivalent to the BDFM.

**Comment by lmweber** [comment]
Ok I think this has worked quite nicely for the seqFISH dataset, as follows:

- standard assay called `counts` containing counts per gene per cell
- second assay called `molecules`, which is a `BumpyMatrix` containing a small data frame for each gene-cell combination, containing the x-y coordinates and intensity of each mRNA molecule for that gene and cell. The number of rows of this data frame is equal to the counts in the first assay.
- the full segmentation vertices of each cell are still stored as lists of x and y coordinates (per vertex) in `colData`. I think I will also update this to a `CompressedSplitDFrameList` as @LTLA suggested above.
- `spatialData` also contains the x and y coordinates of the centroids of the cells

Will need to wait until we have pushed all our recent `SpatialExperiment` updates back into Bioc-devel to finish testing (since `BumpyMatrix` is only in devel and can't be installed from GitHub in release due to a conflict), but I think this works.

And this definitely means we do not need the sub-classes (for spot-based and molecule-based) that we were previously thinking about.

My example is here: https://github.com/lmweber/STdata/blob/main/inst/scripts/make-data-seqfish-mouseEmbryo.R

**Comment by lmweber** [comment]
The `SplitDataFrameList` is also very cool - I did not know about this previously.

Turns out it is really easy to reshape the previous format (separate lists for x and y coordinates) with:

```
seg_verts <- SplitDataFrameList(
  x_coord = col_data$segmentation_vertices_x_global_affine, 
  y_coord = col_data$segmentation_vertices_y_global_affine, 
  cbindArgs = TRUE
)
```

And then put this back into `colData`. Also need to use `DataFrame()` and `I()` when `cbinding` this column to avoid conversion problems.
