### ISSUE TITLE
Potential new`.parquet` format for `tissue_position` of VisiumHD might trigger issues for `read10xVisium`

### ISSUE THREAD

**Issue by boyiguo1** [drighelli/SpatialExperiment#150]
Thanks for creating and maintaining the package.

I'm experimenting the `SpatialExperiment::read10xVisium`to import the Visium HD data via https://www.10xgenomics.com/datasets/visium-hd-cytassist-gene-expression-libraries-of-mouse-brain-he.

I noticed in this example data, specifically default Spaceranger output `square_008um_outputs.tar.gz` (unzipped and `outs` folder created), they changed the format for the `tissue_position` file from `.csv` to `.parquet`.
```batch
>tree spatial
spatial
├── aligned_fiducials.jpg
├── aligned_tissue_image.jpg
├── cytassist_image.tiff
├── detected_tissue_image.jpg
├── scalefactors_json.json
├── tissue_hires_image.png
├── tissue_lowres_image.png
└── tissue_positions.parquet
```

This seems to both cause problem when setting names for `xyz` because the function only detects `.csv` files,
https://github.com/drighelli/SpatialExperiment/blob/cfd929f7310e3f85c966e7d56b661a0ba99b40b6/R/read10xVisium.R#L132-L139,
and the error reports on L139 due to `xyz` is a character vector of length zero. 
```{r}
Error in names(xyz) <- names(sfs) <- sids : 
  'names' attribute [1] must be the same length as the vector [0]
```

Secondly, the current implementation `.read_xyz` doesn't seem to be compatible to read in `.parquet` file. 

The parquet file may be able to be loaded via https://www.rdocumentation.org/packages/arrow/versions/0.14.1/topics/read_parquet.

Thanks!

**Comment by wangjiawen2013** [comment]
I met the same error, but solved by https://github.com/drighelli/SpatialExperiment/issues/118

**Comment by drighelli** [comment]
hi @boyiguo1, 

unfortunately, we don't support the import for the 10x Visium HD data yet.

I'll keep this issue open for further developments.

Thanks,
Dario

**Comment by alikhuseynov** [comment]
We added support to load VisiumHD in `SpatialFeatureExperiment`, where modified `SpatialExperiment::read10xVisium` is used -> https://github.com/pachterlab/SpatialFeatureExperiment/blob/devel/R/read.R#L223-L324

@drighelli if you guys are interested, we could do a PR on that.

cheers

**Comment by drighelli** [comment]
Thanks @alikhuseynov that would be nice!

I'm also reporting that Marcel ( @LiNk-NY ) developed the [VisiumIO package](https://github.com/waldronlab/VisiumIO), please give it a shot :)

**Comment by alikhuseynov** [comment]
> Thanks @alikhuseynov that would be nice!
> 
> I'm also reporting that Marcel ( @LiNk-NY ) developed the [VisiumIO package](https://github.com/waldronlab/VisiumIO), please give it a shot :)

Thanks! I will try to PR, I'm including @lambdamoses as well here.
Yeah, I saw that package as well, but it doesn't provide VisiumHD loader (maybe be it is under development?)

**Comment by drighelli** [comment]
I think VisiumIO is in Bioconductor, but it has been developed before the Visium HD release!

**Comment by drighelli** [comment]
Quick heads-up, `read10xVisium` will be deprecated during future releases of `SpatialExperiment`.

We added a warning for this function, we strongly encourage to start use `VisiumIO` package

If interested in a PR, we suggest to do it on the `VisiumIO` package.

Thanks.

**Comment by alikhuseynov** [comment]
ok, thanks for the update.
