### ISSUE TITLE
spatialData/spatialCoords arguments in constructor

### ISSUE THREAD

**Issue by lmweber** [drighelli/SpatialExperiment#17]
Now that we have both `spatialData` and `spatialCoords` accessors, we should also think about consistency for the `SpatialExperiment` constructor.

E.g. `spatialCoords` accessor returns a matrix, but `spatialCoords` argument in the constructor accepts a `DataFrame`.

Maybe one option is to simply replace the argument in the constructor, so have an argument `spatialData` instead of `spatialCoords`:

```
SpatialExperiment(
  ...,
  sample_id = "Sample01",
  spatialData = NULL,
  scaleFactors = 1,
  imageSources = NULL,
  image_id = NULL,
  loadImage = TRUE,
  imgData = NULL
)
```

**Comment by drighelli** [comment]
You're right, I forgot to correct that argument!

**Comment by lmweber** [comment]
Update from today's testing:

- `spatialData` accessor is now working
- argument name in constructor needs to be changed from `spatialCoords` to `spatialData`

Thanks!

**Comment by drighelli** [comment]
done
