### ISSUE TITLE
?SpatialImage should document the preferred sources

### ISSUE THREAD

**Issue by LTLA** [drighelli/SpatialExperiment#24]
I can't remember what @HelenaLC and I discussed, but there was an order to what was checked to get the image. Maybe it was:

- The loaded grob, if available
- The file path
- The URL? Can't remember.

Roughly in order of how much effort it would take to load it into the R session.

Come to think of it, what was the use case for the URL again? Seems like we'd always be caching the image locally anyway.

**Comment by LTLA** [comment]
Actually, I have a better idea that will solve this problem and allow us to do cool things.

Define the virtual `SpatialImage` class along with the `imgGrob` generic. This is the base class and has a single slot that can be filled with the grob. (This slot can also be empty.) 

Define a `InMemorySpatialImage` subclass that enforces the constraint that the slot is not empty. This supports the case where we just have pure R objects containing images with no interaction with the file system.

Define a `LocalSpatialImage` subclass of `SpatialImage` that contains an additional slot for the file path. When `imgGrob()` is called, if the grob is not loaded, it will be fetched from the file system. 

Define a `RemoteSpatialImage` subclass of `SpatialImage` that contains an additional slot for the URL.  When `imgGrob()` is called, if the grob is not loaded, it will be fetched from the specified URL. (Possibly with caching.)

`loadImg` and related generics will be no-ops for some of these functions - that's okay.

With this hierarchy, we obtain a more scalable method for including different sources of images. It's easy to reason about where an image comes from by simply looking at its class, rather than trying to go down a list of possible sources. Moreover, it gives certain smart people a chance to write further subclasses, e.g., to pull from internal data sources, AWS S3, etc.

**Comment by LTLA** [comment]
In fact, thinking about it further, one can use the class hierarchy to clarify things further.

- `SpatialImage`, base class, virtual, no slots.
- `LoadedSpatialImage`, inherits from `SpatialImage`, one slot containing grob (or raster, see #27). Must be filled.
- `CachedSpatialImage`, inherits from `SpatialImage`, virtual, no slots. I'll get back to this.
- `FileSpatialImage`, inherits from `CachedSpatialImage`, one slot containing the file path, no slot for the raster.
- `RemoteSpatialImage`, inherits from `CachedSpatialImage`, one slot containing the URL, no slot for the raster.

Then, `loadImg()` will simply convert `FileSpatialImage` or `RemoteSpatialImage` to a `LoadedSpatialImage`. Nice and clean, you can instantly tell whether an image is loaded or not by just looking at the `SpatialImage` subclass identity. While this does lose the file path/URL, I don't think that's a big deal - it's not like our count matrices remember the file that they're loaded from.

The issue (with the current and previously proposed approach) is that people have to remember to call `loadImg()` if they don't want to have to pay the cost for every image in memory every time they call `imgGrob()`. To make life easier, we can set up an in-memory pass-by-reference caching system. This will silently cache the loaded image on first use of `imgGrob()` for a particular instance of a `CachedSpatialImage`. To illustrate:

```r
cache.env <- new.env()
cache.env$cache <- list()

.imgGrob <- function(x) {
    cur.cache <- cache.env$cache[[class(x)[1]]]
    if (is.null(cur.cache)) cur.cache <- list()
    available <- cur.cache[[x@path]]
    if (is.null(available)) {
        cur.cache[[x@path]] <- available <- load_image(x@path)
        cache.env$cache[[class(x)[1]]] <- tail(cur.cache, 5)
     } else {
         reorder <- c(setdiff(names(cur.cache), x@path), x@path) # move last used to end.
         cur.cache <- cur.cache[reorder]
    }
    available
}
```

When this function is called the first time, it will add its image to `cache.env` as a side effect. And if it is called subsequently, it will attempt to retrieve said image from the cache, rather than loading it again. This allows users to transparently obtain the performance of a `LoadedSpatialImage` from a `CachedSpatialImage` subclass. You can also see how we only retain the last 5 used images to save memory, under the assumption that a recently used image will most likely be re-used soon. 

For additional sophistication, the size of the cache can be determined from the total number of pixels across all images held in the cache. This can be further multiplied by the size of the string pointers to estimate the memory usage, giving us the **DelayedArray**-like capability of saying, "Okay, total size of the image cache should not exceed 100 MB."

**Comment by dtm2451** [comment]
I don't know enough about how easy or hard it may be to define new classes like this, so I won't comment yes or no on @LTLA's proposed mechanism above. I will however, present a potential (possibly common) edge-case when having a non-intelligent cache size limit might become quite inefficient?: When all slides of an experiment are plotted one after another multiple times (maybe showing expression of different genes, where facets = slides) there could be a continuous cycle of cache-uncache-cache-uncache as soon as the imageData / slide number grows large enough to overwhelm the size limit.

But the main reason I'm here is just to second the desire for an efficient & reliable `loadImg()` method which gets addressed here. Specifically, a single function call that would reliably get me from knowing which rows of imgData I want images for -> those grobs (or rasters).  I don't particularly care whether it's the method above or something different, I'd just like it to work no matter how the image is currently stored.

**Comment by LTLA** [comment]
> When all slides of an experiment are plotted one after another multiple times (maybe showing expression of different genes, where facets = slides) there could be a continuous cycle of cache-uncache-cache-uncache as soon as the imageData / slide number grows large enough to overwhelm the size limit.

Yes. At that point, a decision must be made on whether you can afford to load all images into memory. This isn't particularly different from the same kind of decisions that one might need to make for count data.

I would design the system so that reading functions like `read10xVisium()` use `MemorySpatialImage`s by default (i.e., load into memory), but users can request to keep things file-backed if they so desire. Most experiments won't have that many images; even 50 images at 2000 x 2000 is still only 1.6 GB with 8 byte pointers to the string cache.

**Comment by HelenaLC** [comment]
Okay, @LTLA I'm slowly getting the idea... I can try to have a crack at implementing this and will get back to you in the certain case that I have questions.

**Comment by HelenaLC** [comment]
Okay, so if I understand correctly, you're imagining something like this (?):

```
#' @export
setClass(
    Class="SpatialImage")

#' @export
setClass(
    Class="LoadedSpatialImage",
    contains="SpatialImage",
    slots=c(grob="grobOrNULL"))

#' @export
setClass(
    Class="CachedSpatialImage",
    contains="SpatialImage"))

#' @export
setClass(
    Class="StoredSpatialImage",
    containes="CachedSpatialImage",
    slots=c(path="charOrNULL"))

#' @export
setClass(
    Class="RemoteSpatialImage",
    contains="CachedSpatialImage",
    slots=c(url="charOrNULL"))
```

The main issue I see with forgetting the path/URL upon loading, and this is why (I think?) we designed it the way it currently is, is that I can imaging one might load images, plot stuff, dance - and then eventually export and object for sharing (e.g. upload with publication or send to others to play with it). 
In such cases, (I think?) we wanted to support unloading the images at some point, but in a way that the next guy can retrieve them (if they were stored at some URL) for example... Thoughts?

**Comment by LTLA** [comment]
> Okay, so if I understand correctly, you're imagining something like this (?):

Very close. I would avoid the temptation to use `OrNuLL`s unless it cannot be avoided, as this weakens the class contract, i.e., a user of a `StoredSpatialImage` couldn't be guaranteed that a file path exists in the class. Makes life more painful downstream as everything must be done with an `is.null` check before the contents can be used.

Also, `SpatialImage` should `contains="VIRTUAL"`, to prevent people from creating objects with no information.

> The main issue I see with forgetting the path/URL upon loading, and this is why (I think?) we designed it the way it currently is, is that I can imaging one might load images, plot stuff, dance - and then eventually export an object for sharing (e.g. upload with publication or send to others to play with it).

Not sure I understand the problem here. A loaded image would be embedded in the object and could be sent around with the rest of the SpE's contents. It shouldn't matter that you don't have the path to the _original_ files, much like we don't bother to store the path to the MTX files alongside the count matrix.

Of course, if you make `StoredSpatialImage`s in your object, then we run into the same kind of problems as we do for `HDF5Array`s when we want to send them around. I'd argue that `StoredSpatialImage`s are strictly for local use anyway.

> In such cases, (I think?) we wanted to support unloading the images at some point, but in a way that the next guy can retrieve them (if they were stored at some URL) for example... Thoughts?

This case can be handled by loading them as a `RemoteSpatialImage` and then bumping up the cache size to effectively mimic a `LoadedSpatialImage`. This avoids the need to explicitly unload anything from the SpE supplier (because the cache doesn't get serialized in the object) and the consumer automatically retrieves them.
