### ISSUE TITLE
Error with sample ID checks when using constructor

### ISSUE THREAD

**Issue by lmweber** [drighelli/SpatialExperiment#30]
When I create an object with the constructor `SpatialExperiment()`, I get an error due to the checks for the sample IDs.

The error occurs even when using the default sample ID of `Sample01`. I'm not sure what is causing it.

It works when I add the sample ID manually in the constructor as an argument (e.g. see working code below), however this should not be required, since the sample IDs are already in `imgData` and/or `colData`.

```
spe <- SpatialExperiment(
  assays = list(counts = counts), 
  rowData = row_data, 
  colData = col_data, 
  spatialData = spatial_data, 
  imgData = img_data, 
  sample_id = "Sample01"
)
```

**Comment by drighelli** [comment]
Are you sure that you are using the latest version of the class? The default sample_id should be “sample_01”

**Comment by lmweber** [comment]
Ah whoops - I still had "Sample01" in my script from the earlier versions. Maybe it will work with "sample_01". We will also need to check that it works with custom sample IDs too.
