### ISSUE TITLE
Enable spatialData(cd_bind) with multiple columns

### ISSUE THREAD

**Issue by lcolladotor** [drighelli/SpatialExperiment#32]
Hi,

Currently this doesn't work:

```R
x <- spatialData(spe, cd_bind = colnames(colData(spe)), as_df = TRUE)
Error in normalizeDoubleBracketSubscript(i, x, exact = exact, allow.NA = TRUE,  : 
  attempt to extract more than one element
```

That's because of the use of the double bracket at https://github.com/drighelli/SpatialExperiment/blob/697fc2ef9b174ffa9b59acefdbce7d7b90fd0727/R/SpatialExperiment-methods.R#L193. 

Changing `colData(x)[[cd_bind]]` to `colData(x)[, cd_bind, drop = FALSE]` should work.

Best,
Leo

**Comment by drighelli** [comment]
thanks!

I'll do it!

**Comment by drighelli** [comment]
fixed with your hint! Thanks!

**Comment by lcolladotor** [comment]
awesome, thanks!
