### ISSUE TITLE
Enable spatialData(cd_bind) to retrieve everything in colData()

### ISSUE THREAD

**Issue by lcolladotor** [drighelli/SpatialExperiment#33]
Hi,

Related to #32, it'd be nice if one had a quick way of using `spatialData(cd_bind)` to retrieve everything in the `colData()` instead of having to write `cd_bind = colnames(colData(spe))` as in #32.

Best,
Leo

**Comment by drighelli** [comment]
now `cd_bind=TRUE` returns what you want. :)
version 1.1.429

**Comment by lcolladotor** [comment]
sweeet!!! thanks!
