### ISSUE TITLE
subset method does not match generic

### ISSUE THREAD

**Issue by LiNk-NY** [drighelli/SpatialExperiment#35]
Hi Dario, 

We're seeing this error occur in the `SingleCellMultiModal` vignette:
http://bioconductor.org/checkResults/devel/data-experiment-LATEST/SingleCellMultiModal/rex3-buildsrc.html
```r
--- re-building ‘seqFISH.Rmd’ using rmarkdown
Quitting from lines 55-59 (seqFISH.Rmd) 
Error: processing vignette 'seqFISH.Rmd' failed with diagnostics:
invalid 'y' type in 'x && y'
```
The reason for this is that the `SpatialExperiment,[-method` does not match
the generic: 
### Method
https://github.com/drighelli/SpatialExperiment/blob/8407ee8ad3a9c31bb4dfa72a3fdda34744dad075/R/subset.R#L27-L29
### Generic
```r
> getGeneric("[")
standardGeneric for "[" defined from package "base"

function (x, i, j, ..., drop = TRUE) 
standardGeneric("[", .Primitive("["))
<bytecode: 0x55baeedbc328>
<environment: 0x55baeedae930>
Methods may be defined for arguments: x, i, j, drop
Use  showMethods("[")  for currently available ones.
```

For an example of creating your own `[` method, see `SummarizedExperiment` starting here: 
https://github.com/Bioconductor/SummarizedExperiment/blob/master/R/SummarizedExperiment-class.R#L418 
In this case, you may not want to use the `drop` argument similarly to what `SummarizedExperiment` does. 

Best,
Marcel

**Comment by drighelli** [comment]
Thanks @LiNk-NY,

I'll fix this as you suggested!

**Comment by drighelli** [comment]
this has been fixed in version 1.1.434 (2021/02/26) on the `devel` branch

**Comment by LiNk-NY** [comment]
Hi Dario, @drighelli 
I don't see this change in Bioconductor devel. 
http://bioconductor.org/checkResults/devel/bioc-LATEST/SpatialExperiment/
Is it ready to be pushed upstream? 
Thanks.
-Marcel

**Comment by drighelli** [comment]
Hi Marcel, the update is not ready yet on the upstream because we're developing some new stuff... 

I hope that it'll be ready in a few days...

**Comment by LiNk-NY** [comment]
@drighelli The builds have already started. Let's keep an eye out for tomorrow's build report. Thanks.

**Comment by drighelli** [comment]
Hi Marcel @LiNk-NY 

I checked on the Bioc build report and it'd be ok now!

Does it work on the `SingleCellMultiModal`?

**Comment by LiNk-NY** [comment]
Hi Dario, @drighelli 
We have to wait for the experiment data package builds which are once a week, I believe. I'll keep an eye out for the report tomorrow.

**Comment by drighelli** [comment]
Hi @LiNk-NY 

could you please confirm that this issue has been already addressed ?

Thanks

**Comment by LiNk-NY** [comment]
It looks good to me. Thanks!
