### ISSUE TITLE
Sample vs sample_id

### ISSUE THREAD

**Issue by lcolladotor** [drighelli/SpatialExperiment#52]
Hi,

Our understanding (@bpardo99 and mine) is that `colData(spe)$sample_id` is where the sample names are stored. For example, as discussed at https://github.com/drighelli/SpatialExperiment/blob/master/vignettes/TENxVisium.Rmd#L147-L154 and overall in that vignette.

It's just that if we run the example from `read10xVisium()` we get both `Sample` and `sample_id` (with the same info) inside `colData()`. That's using the version from the latest commit (https://github.com/drighelli/SpatialExperiment/commit/17e5176fd6a3b3eea513c2595310d9e49cfb7fb3) in the `master` branch.

Brenda is updating `spatialLIBD::sce_to_spe()` since @jvelezmagic  reported at https://github.com/LieberInstitute/spatialLIBD/issues/11 that `barcode` now is called `Barcode` and lives in `colData()` instead of `spatialData()`.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi Dario,

No worries!

Hmm, I don't see any recent changes at https://github.com/drighelli/SpatialExperiment/blob/master/R/read10xVisium.R. It might be on another branch or fork. Anyways, are you going to use `sample_id`? Or `Sample`?

Best,
Leo

**Comment by drighelli** [comment]
ops sorry I forgot to mention this, we are working on the spatialCoordsData branch at the moment.

Anyway, we're going to use the `sample_id` field.

Dario

**Comment by lcolladotor** [comment]
Ok! thanks!

Around when are you thinking of making the new changes? Just so we can keep that in mind given https://www.bioconductor.org/developers/release-schedule/ and so we can update `spatialLIBD` if needed.

**Comment by drighelli** [comment]
Hopefully, first half of the next week...

**Comment by lcolladotor** [comment]
ok =) sounds good ^^
