### ISSUE TITLE
spatialCoords should not be stored in the colData when built from it

### ISSUE THREAD

**Issue by drighelli** [drighelli/SpatialExperiment#53]
At the moment when building the spatialCoords and spatialData from the colData the object still stores the coordinates into the colData, a possible solution could be to drop them when storing elsewhere.

A reproducible example

```
cd <- DataFrame(x=1:26, y=1:26, z=letters)
mat <- matrix(nrow=26, ncol=26)
spe <- SpatialExperiment(assay=mat, colData=cd, spatialCoordsNames=c("x", "y"), spatialDataNames="z")
spatialData(spe)
head(spatialCoords(spe))
colData(spe)
```

**Comment by HelenaLC** [comment]
resolved by PR #54
