### ISSUE TITLE
Design question: how to best organize multiple Visium images: one VisiumExperiment object or a list of them?

### ISSUE THREAD

**Issue by lcolladotor** [drighelli/SpatialExperiment#6]
Hi Dario,

Brenda @bpardo99 is helping me with re-casting our `spatialLIBD` Visium data to use your package. We plan to update our functions such that they can work with data in your new `VisiumExperiment` class. However, we have a quick design question. We initially created a SCE object with the data for 12 Visium images. With `VisiumExperiment`, should we create 12 objects or can we actually make a single large one with the data from all 12 images? At some point, we have functions in `spatialLIBD` that benefit from having the data for all images, though we can work also with a list of 12 objects.

Like, maybe we can add a "sample_id" to the `spatialCoords` since the barcodes (currently `Cell_ID` http://bioconductor.org/packages/devel/bioc/vignettes/SpatialExperiment/inst/doc/MouseCoronalVisiumAnalysis.html#retrieving-spatial-coordinates) get repeated (say `ACGCCTGACACGCGCT-1` is the first line for both https://github.com/LieberInstitute/HumanPilot/blob/master/10X/151507/tissue_positions_list.txt and https://github.com/LieberInstitute/HumanPilot/blob/master/10X/151508/tissue_positions_list.txt). We can make them unique, by pasting the `sample_id` to the barcode value also. Maybe these values don't have to be unique for the class to work well. 

Though, if we had a `image_id` or `sample_id` column, we could then have the data all in one object, and have a "subset_by_sample" function. 

Anyway, let me know if this is clear. If you want to, we would also be happy to video chat and clarify anything that's unclear.

Thanks,
Leo

**Comment by lcolladotor** [comment]
Also, the `sample_id` could be on the `colData()` slot, which is what we currently do using SCE. Then we can subset using the `[, col]` syntax though we also then need to subset the image paths (images for us right now) which is what we do at say http://research.libd.org/spatialLIBD/reference/geom_spatial.html.

**Comment by drighelli** [comment]
Hi Leonardo,

I'm not sure what you're saying, I'll try to recapitulate.

You have 12 different images of 12 different experiments, if this is right, why not using a MultyAssayExperiment class within 12 different VisiumExperiment (VE) objects? You should have access to a series of additional features such as the samples  subset across the VEs.

What do you think?

Dario

**Comment by lcolladotor** [comment]
Interesting, I hadn't thought of using MAE. Thanks for the suggestion Dario! I'll talk with Brenda about it later today.

Best,
Leo

**Comment by drighelli** [comment]
Let me know if it works for you! :)
dario

**Comment by lcolladotor** [comment]
I'll close this issue since we had a meeting about this R package on Monday with Dario and others. Several changes were proposed and discussed that are being tracked elsewhere.
