### ISSUE TITLE
Coercing from an SCE to a SPE

### ISSUE THREAD

**Issue by LTLA** [drighelli/SpatialExperiment#73]
I don't see how to easily do this right now. There are three options, one of which is better than the others:

1. Define a `setAs` method. Not ideal as there are no appropriate "zero" values for some fields, e.g., the coordinates, image data. 
2. Constructor checks if the supplied argument list contains an SCE and skips the internal SCE construction. This is not consistent with the behavior of the SE and SCE constructors, which do not perform these checks.
3. Add a dedicated function like `toSpatialExperiment`, which basically calls `.sce_to_spe` with the same arguments as those in the constructor, possibly after promotion of SEs and RSEs to SCE.

The third option seems best.

**Comment by drighelli** [comment]
Hi Aaron (@LTLA),

I'm not sure about this issue, we already have a coercion method (that for sure needs to be updated with the removal of the sample_id argument [here](https://github.com/drighelli/SpatialExperiment/blob/master/R/SpatialExperiment.R#L350)), but it's already there.

I think that once fixed this should be enough...

**Comment by LTLA** [comment]
But when you coerce an SCE to an SPE, what are the "default" coordinates and spatial data? What are the "default" sample IDs? I'm seeing zero-column DFs and matrices for `spatialData` and `spatialCoords`; is this even a semantically valid object? If I gave this object to downstream applications, I have little doubt that they would just break.

**Comment by drighelli** [comment]
When coercing, the defaults values are the same provided in the constructor, we followed the SCE initialization idea:
an empty `DataFrame` for the `spatialData` and an empty `matrix` for the `spatialCoords`.
At the same time the `sample01` `sample_id` is assigned and bound to the existing `colData`.

**Comment by drighelli** [comment]
I started to address the issue [here](https://github.com/drighelli/SpatialExperiment/pull/81) .

Happy to have more discussion though

**Comment by LTLA** [comment]
> When coercing, the defaults values are the same provided in the constructor, we followed the SCE initialization idea:
> an empty `DataFrame` for the `spatialData` and an empty `matrix` for the `spatialCoords`.
> At the same time the `sample01` `sample_id` is assigned and bound to the existing `colData`.

The initialization philosophy for `reducedDims` and `altExps` is quite a bit different. It would be fairly reasonable to see a SCE with no reduced dims or alternative experiments. And downstream functions do not assume that such entries already exist, as they are incrementally added to the object throughout the lifetime of the analysis.

The question here is, would it be reasonable to see a SPE with no coordinates or spatial data? A downstream package developer might reasonably assume that an SPE will always contain a 2-column (or 3-column) matrix of spatial coordinates, as this information should be known at the start of the analysis. An SPE with a no-column matrix of coordinates, no spatial data and no images is practically useless as an SPE, and if you loosen the "SPE user contract" to allow this to happen, it means that a downstream developer can't rely on the sensible existence of any of the SPE slots when an SPE is provided.

**Comment by drighelli** [comment]
Hi Aaron, 

we just spoke about your latest point and we agree with you about this possible scenario.

> 3. Add a dedicated function like toSpatialExperiment, which basically calls .sce_to_spe with the same arguments as those in the constructor, possibly after promotion of SEs and RSEs to SCE.

Now it's also clearer why this point seems the best to solve this issue.

We'll work on it and keep you updated.

Thanks

**Comment by lmweber** [comment]
This has now been addressed in pull request #81
