### ISSUE TITLE
Errors in show method for the SpatialImage

### ISSUE THREAD

**Issue by LTLA** [drighelli/SpatialExperiment#74]
```
> example(SpatialImage)

SptlIm> path <- system.file(
SptlIm+   "extdata", "10xVisium", "section1", "spatial",
SptlIm+   "tissue_lowres_image.png", package="SpatialExperiment")

SptlIm> spi <- SpatialImage(path)

SptlIm> plot(imgRaster(spi))
Hit <Return> to see next plot:
> spi
A 600 x 576 StoredSpatialImage
imgSource():
  /Users/luna/Software/R/R-4-1-branch-dev/
  library/SpatialExperiment/extdata/10xVis
  ium/section1/spatial/tissue_lowres_image
  .png>
```

- Lacking a trailing newline so the prompt appears at the end of the path.
- Dimensions are flipped; number of rows in the raster is actually the height, while number of columns is the width.

I would also argue that the source is excessively wrapped. Why not follow the default 80 character width?

**Comment by drighelli** [comment]
Hi Aaron (@LTLA),

thanks for reporting us this issue, I'm just fixing the show method.

I've only one question about the "flipped" dimensions because we're just reporting the dimensions as provided by the raster.
What do you mean by your comment? That the printed 600 is referred to the number of columns?

**Comment by LTLA** [comment]
600 x 576 refers to the number of rows and number of columns in the raster object. However, when reporting image dimensions, it is typical to use "width x height". In such cases, the number of rows = height, and the number of columns = width, i.e., flipped.

**Comment by drighelli** [comment]
Thanks for clarifying this point Aaron, I made a PR with all the suggestions you provided.
About the flipping, after a few more discussions with Davide and Lukas, we decided to clearly specify the width and height in the show method, flipping them as you suggested.
