### ISSUE TITLE
Add a filepath= argument to the imgSource generic

### ISSUE THREAD

**Issue by LTLA** [drighelli/SpatialExperiment#75]
Currently, the `imgSource` generic is not guaranteed to return a file path. It could return a path, or it could return a URL, or it could return `NA` (e.g., for a `LoadedSpatialImage`), or something else like a database identifier. This makes it difficult to use programmatically as clients would need to adapt to all sorts of possible definitions for the source.

We can restore order by providing a `filepath=TRUE` option that forces all methods to return an actual file path. For the `StoredSpatialImage` objects, this is trivial, but even `RemoteSpatialImage` objects can return a path to their cached file. This ensures that downstream package (e.g., **magick**) can operate on the original source file.

**Comment by LTLA** [comment]
Sorry for the late reply - the summary of the methods looks good. 

For the SPE methods, I'm asssuming you're referring to `imgSource`; in that case, I would put `path` at the very end as this is a less important argument than identifying the correct image in the first place. Of course, you can just leave it in `...` instead.

**Comment by HelenaLC** [comment]
addressed in PR #92

**Comment by LTLA** [comment]
Didn't notice your final question: I wouldn't worry about checking validity, I'd just assume it's valid and exists. You can just put that in the documentation for developers, I think it would be obvious that they should not return a non-existent path.
