### ISSUE TITLE
Inconsistency in default column names for spatialCoords

### ISSUE THREAD

**Issue by lmweber** [drighelli/SpatialExperiment#79]
Another minor issue I found just now - we have an inconsistency between the default column names for `spatialCoords` between the `SpatialExperiment()` constructor and `read10xVisium()`.

`SpatialExperiment()` uses `c("x", "y")`, and `read10xVisium()` uses `c("pxl_col_in_fullres", "pxl_row_in_fullres")` from Space Ranger.

I'm not sure if we need to change this, but we can also discuss in our next meeting.

The relevant line of code is here: https://github.com/drighelli/SpatialExperiment/blob/master/R/read10xVisium.R#L159

**Comment by lmweber** [comment]
Alternatively we could also provide this as an argument, either directly or with `...`.

**Comment by drighelli** [comment]
I think that in the constructor case it's better to stay more general, while for the visium it's ok to stick with the specific visium names

**Comment by lmweber** [comment]
As discussed today in our meeting and @drighelli mentioned above - we prefer to leave this as is, i.e. the base constructor `SpatialExperiment()` uses `c("x", "y")` for the more general case, and `read10xVisium()` uses the more specific `c("pxl_col_in_fullres", "pxl_row_in_fullres")` from Space Ranger.

**Comment by lmweber** [comment]
And noting that users can easily change the column names of `spatialCoords` after creating the object if they prefer different names.
