### ISSUE TITLE
move spatialData from int_colData to colData

### ISSUE THREAD

**Issue by HelenaLC** [drighelli/SpatialExperiment#84]
Related to #82. What d'ya think @LTLA?  
- store all spatial metadata inside `colData`  
(e.g., upon *de novo* SpE construction or with `read10xVisium`)
- drop additional arguments from both accessors (i.e., `colData` and `spatialData`);  
`colData` should return all sample-level metadata, and `spatialData` a subset thereof
- keep track of spatial metadata via `int_metadata` slot `spatialDataNames`  
(character vector specifying which `colData` columns hold spatial metadata)
- `spatialDataNames/names(colData)/colData<-` should assure that these are in synch

*Food for thought: In principal, one could argue that `spatialData` are not that special. Or at least not more special than other experiment metadata (e.g., sample identifiers, treatment etc.). Thus, an open point for discussion is whether we even need `spatialDataNames`. Pros: Keep track of what's spatial. Cons: Confusion / perhaps unnecessarily complicated design. Opinions?*

**Comment by lmweber** [comment]
This has now been addressed in PR #94 so I think we can close this issue
